### ISSUE TITLE
todo: bucket list before presentation

### ISSUE THREAD

**Issue by artemagvanian** [cs0320-s2023/final-project-afunk3-jhirschh-aagvania-hpeter11#1]
## Frontend

- [ ] saving into localStorage
- [x] exporting the schedule
- [x] sync with the backend
- [x] css styling of the interface
- [ ] tests, tests, tests
- [x] how-to popup/button
- [ ] documentation

## Backend

- [x] api testing – @hpeter11 
- [ ] finish data collection – @hpeter11 
- [x] documentation – @artemagvanian 
- [x] not adding extra courses to the past semesters – @artemagvanian 

## Slideshow
- [ ] slideshow
